#!/usr/bin/env bash
# Regenerates every .out. Run from anywhere. Never patches repo sources:
# the parser is generated by yecc from the UNMODIFIED compiler/src/bs_parser.yrl,
# the other modules are erlc-compiled from the UNMODIFIED repo files; only the
# lexer (needs OTP 28 leex TokenLoc) is replaced by probes/lex_mini.erl.
set -u
here=$(cd "$(dirname "$0")" && pwd); repo=$(cd "$here/../../.." && pwd)
b=$here/build; rm -rf "$b"; mkdir -p "$b"; cd "$here"
{ echo "== erl";  erl -noshell -eval 'io:format("OTP ~s erts ~s~n",[erlang:system_info(otp_release),erlang:system_info(version)]),halt().'
  echo "== elixir"; elixir --version | tail -1
  echo "== elm"; elm --version
  echo "== gleam"; echo "not probed (not installed; install denied)"
  echo "== repo sources hashed"; (cd "$repo/compiler/src" && sha256sum bs_parser.yrl bs_check.erl bs_types.erl bs_emit.erl); git -C "$repo" rev-parse HEAD
} > versions.out 2>&1
erl -noshell -eval 'io:format("~p~n",[yecc:file("'$repo'/compiler/src/bs_parser.yrl",[{parserfile,"'$b'/bs_parser.erl"},{report,false},{verbose,false}])]),halt().' > build.out 2>&1
for f in bs_types bs_check bs_diag bs_emit bs_lower bs_otp; do erlc -o "$b" +debug_info "$repo/compiler/src/$f.erl" >> build.out 2>&1; done
erlc -o "$b" "$b/bs_parser.erl" >> build.out 2>&1
for p in bsc_pieces; do escript $p.escript > $p.out 2>&1; done
escript erlang_stages.escript > erlang_stages.out 2>&1
elixir elixir_forms.exs > elixir_forms.out 2>&1
escript sizes_cost.escript > sizes_cost.out 2>&1
./call_sites.sh > call_sites.out 2>&1
escript fold_prototype.escript > fold_prototype.out 2>&1
[ -x elm_probe.sh ] && ./elm_probe.sh > elm_probe.out 2>&1
exit 0
