# Do not manually edit this file, it is managed by Gleam.
#
# This file locks the dependency versions used, to make your build
# deterministic and to prevent unexpected versions from being included
# in your application.
#
# You should check this file into your source control repository.

packages = [
  { name = "lib", version = "1.0.0", build_tools = ["gleam"], requirements = [], source = "local", path = "../lib" },
]

[requirements]
lib = { path = "../lib" }
