-module(m).
-export([main/0]).
t(Label, Bin) ->
    R = try json:decode(Bin) of V -> {ok, V} catch C:E -> {C, E} end,
    io:format("~s~n  in:  ~p~n  out: ~p~n", [Label, Bin, R]).
main() ->
    t("valid object", <<"{\"a\":1,\"b\":null}">>),
    t("not json", <<"hello">>),
    t("empty", <<>>),
    t("whitespace only", <<"  ">>),
    t("truncated object", <<"{\"a\":">>),
    t("truncated string", <<"\"abc">>),
    t("trailing data", <<"{\"a\":1} x">>),
    t("trailing second value", <<"1 2">>),
    t("trailing whitespace", <<"1  \n">>),
    t("duplicate keys", <<"{\"a\":1,\"a\":2}">>),
    t("invalid utf8 in string", <<"\"", 16#ff, "\"">>),
    t("invalid utf8 in key", <<"{\"", 16#c3, 16#28, "\":1}">>),
    t("overlong utf8", <<"\"", 16#c0, 16#af, "\"">>),
    t("utf8 surrogate bytes", <<"\"", 16#ed, 16#a0, 16#80, "\"">>),
    t("lone surrogate escape", <<"\"\\ud800\"">>),
    t("surrogate pair escape", <<"\"\\ud83d\\ude00\"">>),
    t("BOM", <<16#ef,16#bb,16#bf,"1">>),
    t("big int", <<"123456789012345678901234567890">>),
    t("int", <<"1">>),
    t("float 1.0", <<"1.0">>),
    t("exp 1e2", <<"1e2">>),
    t("exp 1E400", <<"1E400">>),
    t("neg zero", <<"-0">>),
    t("neg zero float", <<"-0.0">>),
    t("leading zero", <<"01">>),
    t("trailing comma", <<"[1,]">>),
    t("single quotes", <<"{'a':1}">>),
    t("NaN", <<"NaN">>),
    t("control char in string", <<"\"a\nb\"">>),
    t("bad escape", <<"\"\\x\"">>),
    t("0.1 precision", <<"0.1">>),
    t("deep precision", <<"1.00000000000000000001">>),
    t("nested dup", <<"{\"a\":{\"k\":1,\"k\":2}}">>),
    L = try json:decode("{\"a\":1}") of V -> {ok,V} catch C:E -> {C,E} end,
    io:format("charlist input: ~p~n", [L]),
    IO = try json:decode([<<"{\"a\"">>, <<":1}">>]) of V2 -> {ok,V2} catch C2:E2 -> {C2,E2} end,
    io:format("iolist input: ~p~n", [IO]),
    D3 = try json:decode(<<"{\"a\":1} x">>, ok, #{}) of V3 -> V3 catch C3:E3 -> {C3,E3} end,
    io:format("decode/3 with trailing: ~p~n", [D3]),
    D4 = try json:decode(<<"{\"a\":">>, ok, #{}) of V4 -> V4 catch C4:E4 -> {C4,E4} end,
    io:format("decode/3 truncated: ~p~n", [D4]),
    D5 = json:decode(<<"{\"a\":1,\"a\":2}">>, ok, #{object_finish => fun(Acc, Old) -> {lists:reverse(Acc), Old} end}),
    io:format("decode/3 object_finish keeping pairs: ~p~n", [D5]),
    D6 = json:decode(<<"{\"a\":null}">>, ok, #{null => undefined}),
    io:format("decode/3 null=>undefined: ~p~n", [D6]),
    D7 = json:decode_start(<<"{\"a\":">>, ok, #{}),
    io:format("decode_start truncated: ~p~n", [D7]),
    D8 = try json:decode(<<"{\"a\":1}">>, ok, #{object_push => fun(K, V8, Acc) -> [{binary_to_existing_atom(K), V8} | Acc] end}) of V9 -> V9 catch C9:E9 -> {C9,E9} end,
    io:format("existing atom keys: ~p~n", [D8]),
    ok.
