const t = (label, f) => { try { console.log(label, "=>", JSON.stringify(f()), ); } catch (e) { console.log(label, "THROWS", e.constructor.name + ": " + e.message); } };
console.log("node", process.version);
t("dup keys", () => JSON.parse('{"a":1,"a":2}'));
t("bigint", () => JSON.parse('12345678901234567890'));
t("bigint as string", () => String(JSON.parse('12345678901234567890')));
t("1.0 isInteger", () => Number.isInteger(JSON.parse('1.0')));
t("NaN", () => JSON.parse('NaN'));
t("trailing", () => JSON.parse('{} x'));
t("empty", () => JSON.parse(''));
t("non-string input 123", () => JSON.parse(123));
t("non-string input null", () => JSON.parse(null));
t("non-string undefined", () => JSON.parse(undefined));
t("Buffer input", () => JSON.parse(Buffer.from('{"a":1}')));
const o = JSON.parse('{"__proto__": {"x": 1}}');
console.log("__proto__ own key:", Object.keys(o), "o.x:", o.x, "proto is Object.prototype:", Object.getPrototypeOf(o) === Object.prototype);
t("reviver context.source", () => JSON.parse('{"n": 12345678901234567890}', (k, v, ctx) => (ctx && ctx.source !== undefined && typeof v === "number") ? "src:" + ctx.source : v));
console.log("JSON.rawJSON", typeof JSON.rawJSON);
t("lone surrogate escape", () => JSON.parse('"\\ud800"').length);
t("TextDecoder fatal invalid utf8", () => new TextDecoder("utf-8", { fatal: true }).decode(new Uint8Array([0x22, 0xff, 0x22])));
t("TextDecoder default invalid utf8", () => new TextDecoder().decode(new Uint8Array([0x22, 0xff, 0x22])));
