#!/bin/sh
# How Gleam declares provenance. Real project created by `gleam new`, a path dependency (hex is
# unreachable from this container: the first build below shows the resolver failing), the generated
# manifest, and an @external to an Erlang module that is not there.
. "$(dirname "$0")/env.sh"
G=/tmp/tc/gleam
rm -rf $W/gl && mkdir -p $W/gl && cd $W/gl
$G new app --skip-git --skip-github >/dev/null 2>&1
echo "== gleam.toml as generated (the ONLY place a dependency is declared)"; grep -n -A3 'dependencies' app/gleam.toml
echo "== build with the default deps: hex unreachable"; (cd app && $G build 2>&1 | tail -4)
echo "== drop the hex deps, add a PATH dependency on the glib fixture"
rm -rf app/test; cp -r $W/glib_src $W/gl/glib_dep && rm -rf glib_dep/build
cat > app/gleam.toml <<'T'
name = "app"
version = "1.0.0"
target = "erlang"

[dependencies]
glib = { path = "../glib_dep" }
T
cat > app/src/app.gleam <<'G'
import glib

pub fn main() -> Int {
  glib.quad(2)
}

// An FFI declaration. Note what it names: a module and a function. No application, no version.
@external(erlang, "Elixir.Greeter", "hello")
pub fn hello(name: String) -> String
G
(cd app && $G build 2>&1 | tail -3; echo "exit=$?")
echo "== manifest.toml, generated by gleam (the resolution record)"; cat -n app/manifest.toml
echo "== the Erlang gleam emitted for the @external: a bare remote call, no app anywhere"
grep -n "Elixir.Greeter" app/build/dev/erlang/app/_gleam_artefacts/app.erl
echo "== is the missing Erlang module detected at compile time? (it compiled above: exit status)"
(cd app && $G build >/dev/null 2>&1; echo "gleam build exit=$?")
echo "== run it: Greeter is absent"
(cd app && erl -noshell -pa build/dev/erlang/*/ebin -eval 'io:format("~p~n", [catch app:hello(<<"x">>)]), halt().' 2>&1 | head -3)
echo "== and an import of a Gleam module that does not exist IS a compile error (provenance checked for Gleam code only)"
cat > app/src/app.gleam <<'G'
import nonesuch
pub fn main() -> Int { nonesuch.f() }
G
(cd app && $G build 2>&1 | tail -9)
