module Mrec50

record R { Id: int, Total: int }

public int Fun1(R r)

Fun1(r) -> r.Total + 1

public int Fun2(R r)

Fun2(r) -> r.Total + 2

public int Fun3(R r)

Fun3(r) -> r.Total + 3

public int Fun4(R r)

Fun4(r) -> r.Total + 4

public int Fun5(R r)

Fun5(r) -> r.Total + 5

public int Fun6(R r)

Fun6(r) -> r.Total + 6

public int Fun7(R r)

Fun7(r) -> r.Total + 7

public int Fun8(R r)

Fun8(r) -> r.Total + 8

public int Fun9(R r)

Fun9(r) -> r.Total + 9

public int Fun10(R r)

Fun10(r) -> r.Total + 10

public int Fun11(R r)

Fun11(r) -> r.Total + 11

public int Fun12(R r)

Fun12(r) -> r.Total + 12

public int Fun13(R r)

Fun13(r) -> r.Total + 13

public int Fun14(R r)

Fun14(r) -> r.Total + 14

public int Fun15(R r)

Fun15(r) -> r.Total + 15

public int Fun16(R r)

Fun16(r) -> r.Total + 16

public int Fun17(R r)

Fun17(r) -> r.Total + 17

public int Fun18(R r)

Fun18(r) -> r.Total + 18

public int Fun19(R r)

Fun19(r) -> r.Total + 19

public int Fun20(R r)

Fun20(r) -> r.Total + 20

public int Fun21(R r)

Fun21(r) -> r.Total + 21

public int Fun22(R r)

Fun22(r) -> r.Total + 22

public int Fun23(R r)

Fun23(r) -> r.Total + 23

public int Fun24(R r)

Fun24(r) -> r.Total + 24

public int Fun25(R r)

Fun25(r) -> r.Total + 25

public int Fun26(R r)

Fun26(r) -> r.Total + 26

public int Fun27(R r)

Fun27(r) -> r.Total + 27

public int Fun28(R r)

Fun28(r) -> r.Total + 28

public int Fun29(R r)

Fun29(r) -> r.Total + 29

public int Fun30(R r)

Fun30(r) -> r.Total + 30

public int Fun31(R r)

Fun31(r) -> r.Total + 31

public int Fun32(R r)

Fun32(r) -> r.Total + 32

public int Fun33(R r)

Fun33(r) -> r.Total + 33

public int Fun34(R r)

Fun34(r) -> r.Total + 34

public int Fun35(R r)

Fun35(r) -> r.Total + 35

public int Fun36(R r)

Fun36(r) -> r.Total + 36

public int Fun37(R r)

Fun37(r) -> r.Total + 37

public int Fun38(R r)

Fun38(r) -> r.Total + 38

public int Fun39(R r)

Fun39(r) -> r.Total + 39

public int Fun40(R r)

Fun40(r) -> r.Total + 40

public int Fun41(R r)

Fun41(r) -> r.Total + 41

public int Fun42(R r)

Fun42(r) -> r.Total + 42

public int Fun43(R r)

Fun43(r) -> r.Total + 43

public int Fun44(R r)

Fun44(r) -> r.Total + 44

public int Fun45(R r)

Fun45(r) -> r.Total + 45

public int Fun46(R r)

Fun46(r) -> r.Total + 46

public int Fun47(R r)

Fun47(r) -> r.Total + 47

public int Fun48(R r)

Fun48(r) -> r.Total + 48

public int Fun49(R r)

Fun49(r) -> r.Total + 49

public int Fun50(R r)

Fun50(r) -> r.Total + 50

