#!/bin/sh
# Records tool versions for every probe. Regenerated by run.sh into versions.out.
echo "date-of-run: (not recorded, keeps output deterministic)"
uname -sr
erl -noshell -eval 'application:load(compiler), io:format("OTP ~s, erts ~s, compiler ~s, jit=~p, arch=~s~n",[erlang:system_info(otp_release),erlang:system_info(version),proplists:get_value(vsn,element(2,application:get_all_key(compiler)) ++ [{vsn,x}]),erlang:system_info(emu_flavor),erlang:system_info(system_architecture)]),halt().'
elixir --version 2>&1 | tail -1
dialyzer --version
elm --version 2>&1 | head -1
echo "gleam: not installed, not probed"
echo "bsc: NOT BUILT (OTP 25 leex lacks TokenLoc); no probe here runs bsc"
nproc | sed 's/^/nproc: /'
