#!/usr/bin/env bash
# Probe: gleam.toml's real generated [dependencies] table (does it carry a
# version constraint by default?), and what `gleam build` does when a
# dependency cannot be resolved -- this sandbox cannot reach repo.hex.pm, which
# turns out to BE the finding for sub-question 1 (name vs. version): Gleam's
# compile step is inseparable from a resolver hitting the network, because the
# constraint it records is a RANGE, not a name.
set -euo pipefail
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"

gleam new demo >/dev/null
echo "=== real gleam.toml generated by 'gleam new' (unedited) ==="
cat demo/gleam.toml

echo
echo "=== gleam build, with the DEFAULT scaffolded dependencies (network required to even resolve) ==="
cd demo
set +e
gleam build
echo "exit: $?"
set -e

echo
echo "=== control: gleam build with NO dependencies and NO import of one -- does it need network at all? ==="
sed -i '/gleam_stdlib/d; /gleeunit/d' gleam.toml
rm -f test/*.gleam
cat > src/demo.gleam <<'EOF'
pub fn main() {
  let x = 1 + 2
  x
}
EOF
gleam build
echo "exit: $?"

echo
echo "=== now import a stdlib module WITHOUT declaring the dependency: what does the compiler say, and WHERE? ==="
cat > src/demo.gleam <<'EOF'
import gleam/io

pub fn main() {
  io.println("hello")
}
EOF
set +e
gleam build
echo "exit: $?"
set -e
